import type { Pool } from "pg";

function partitionName(date: Date): string {
  const y = date.getUTCFullYear();
  const m = String(date.getUTCMonth() + 1).padStart(2, "0");
  const d = String(date.getUTCDate()).padStart(2, "0");
  return `logs_p${y}${m}${d}`;
}

function dayBounds(date: Date): { start: string; end: string } {
  const start = new Date(
    Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()),
  );
  const end = new Date(start.getTime() + 24 * 60 * 60 * 1000);
  return { start: start.toISOString(), end: end.toISOString() };
}

function quoteIdentifier(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

// Partition bounds in `PARTITION OF ... FOR VALUES FROM (...) TO (...)` must
// be constant literals — PostgreSQL's DDL grammar cannot bind them as query
// parameters. Inputs here are always ISO timestamps generated by
// `dayBounds`, never user input, so a plain escaped string literal is safe.
function quoteLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

async function ensurePartitionForDay(pool: Pool, date: Date): Promise<void> {
  const name = partitionName(date);
  const { start, end } = dayBounds(date);

  const existing = await pool.query("SELECT 1 FROM pg_class WHERE relname = $1", [name]);
  if (existing.rowCount && existing.rowCount > 0) return;

  try {
    await pool.query(
      `CREATE TABLE ${quoteIdentifier(name)} PARTITION OF logs FOR VALUES FROM (${quoteLiteral(start)}) TO (${quoteLiteral(end)})`,
    );
  } catch (err) {
    // Another instance created it concurrently between our check and CREATE.
    const alreadyExists = err instanceof Error && "code" in err && (err as { code: string }).code === "42P07";
    if (!alreadyExists) throw err;
  }
}

/**
 * Pre-creates daily partitions covering [today - behindDays, today + aheadDays].
 * Idempotent; safe to call repeatedly from a timer.
 */
export async function ensureRecentPartitions(
  pool: Pool,
  behindDays: number,
  aheadDays: number,
): Promise<void> {
  const now = new Date();
  for (let offset = -behindDays; offset <= aheadDays; offset++) {
    const day = new Date(now.getTime() + offset * 24 * 60 * 60 * 1000);
    await ensurePartitionForDay(pool, day);
  }
}

export interface PartitionInfo {
  name: string;
  upperBound: Date;
}

const PARTITION_NAME_RE = /^logs_p(\d{4})(\d{2})(\d{2})$/;

/**
 * Lists the daily `logs_pYYYYMMDD` partitions and their upper time bound.
 * The bound is derived from the name itself (which we control) rather than
 * parsed out of the partition's catalog expression, since every partition
 * this service creates is named after its own day boundary.
 */
export async function listDailyPartitions(pool: Pool): Promise<PartitionInfo[]> {
  const { rows } = await pool.query<{ name: string }>(
    `SELECT child.relname AS name
     FROM pg_inherits
     JOIN pg_class parent ON pg_inherits.inhparent = parent.oid
     JOIN pg_class child ON pg_inherits.inhrelid = child.oid
     WHERE parent.relname = 'logs' AND child.relname LIKE 'logs\\_p%'`,
  );

  const partitions: PartitionInfo[] = [];
  for (const row of rows) {
    const match = PARTITION_NAME_RE.exec(row.name);
    if (!match) continue;
    const [, y, m, d] = match as unknown as [string, string, string, string];
    const dayStart = new Date(Date.UTC(Number(y), Number(m) - 1, Number(d)));
    const upperBound = new Date(dayStart.getTime() + 24 * 60 * 60 * 1000);
    partitions.push({ name: row.name, upperBound });
  }
  return partitions;
}

/**
 * Drops a partition outright. This is a metadata-only operation (no row
 * scan, no per-row WAL) so it neither holds a long lock nor bloats the
 * heap the way `DELETE FROM logs WHERE ...` would.
 */
export async function dropPartition(pool: Pool, name: string): Promise<void> {
  await pool.query(`DROP TABLE IF EXISTS ${quoteIdentifier(name)}`);
}

export function startPartitionMaintenanceLoop(
  pool: Pool,
  behindDays: number,
  aheadDays: number,
  intervalMs: number,
): () => void {
  const tick = async (): Promise<void> => {
    try {
      await ensureRecentPartitions(pool, behindDays, aheadDays);
    } catch (err) {
      console.error("Partition maintenance failed", err);
    }
  };

  const handle = setInterval(tick, intervalMs);
  return () => clearInterval(handle);
}
