import type { Pool } from "pg";

// Each partition covers a 7-day period rather than a single day. Query
// planning time for the partitioned `logs` table scales with the number
// of partitions that exist (Postgres must evaluate every partition's
// range against the query at plan time, even ones it ultimately prunes) —
// measured directly via EXPLAIN (ANALYZE, BUFFERS): with ~34 daily
// partitions for a 30-day retention window, planning took ~20-59ms versus
// ~2-5ms of actual execution, on every single GET /logs and
// GET /logs/aggregate call regardless of how selective the filters were.
// Weekly partitions cover the same window with ~5 partitions instead of
// ~34, cutting that fixed per-query overhead by roughly the same factor
// while each partition is still small enough (low hundreds of thousands
// of rows at this project's scale) to keep index-only scans and inserts
// fast. The trade-off is coarser retention granularity — see
// README's Known limitations.
const PARTITION_PERIOD_MS = 7 * 24 * 60 * 60 * 1000;

export function periodStart(date: Date): Date {
  return new Date(Math.floor(date.getTime() / PARTITION_PERIOD_MS) * PARTITION_PERIOD_MS);
}

export function partitionName(start: Date): string {
  const y = start.getUTCFullYear();
  const m = String(start.getUTCMonth() + 1).padStart(2, "0");
  const d = String(start.getUTCDate()).padStart(2, "0");
  return `logs_w${y}${m}${d}`;
}

function periodBounds(start: Date): { start: string; end: string } {
  const end = new Date(start.getTime() + PARTITION_PERIOD_MS);
  return { start: start.toISOString(), end: end.toISOString() };
}

function quoteIdentifier(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

// Partition bounds in `PARTITION OF ... FOR VALUES FROM (...) TO (...)` must
// be constant literals — PostgreSQL's DDL grammar cannot bind them as query
// parameters. Inputs here are always ISO timestamps generated by
// `periodBounds`, never user input, so a plain escaped string literal is safe.
function quoteLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

async function ensurePartitionForPeriod(pool: Pool, periodStartDate: Date): Promise<void> {
  const name = partitionName(periodStartDate);
  const { start, end } = periodBounds(periodStartDate);

  const existing = await pool.query("SELECT 1 FROM pg_class WHERE relname = $1", [name]);
  if (existing.rowCount && existing.rowCount > 0) return;

  try {
    await pool.query(
      `CREATE TABLE ${quoteIdentifier(name)} PARTITION OF logs FOR VALUES FROM (${quoteLiteral(start)}) TO (${quoteLiteral(end)})`,
    );
  } catch (err) {
    // Another instance created it concurrently between our check and CREATE.
    const alreadyExists = err instanceof Error && "code" in err && (err as { code: string }).code === "42P07";
    if (!alreadyExists) throw err;
  }
}

/**
 * Pre-creates the weekly partitions covering [today - behindDays, today +
 * aheadDays] (rounded outward to whole partition periods). Idempotent;
 * safe to call repeatedly from a timer.
 */
export async function ensureRecentPartitions(
  pool: Pool,
  behindDays: number,
  aheadDays: number,
): Promise<void> {
  const now = Date.now();
  const earliest = periodStart(new Date(now - behindDays * 24 * 60 * 60 * 1000));
  const latest = periodStart(new Date(now + aheadDays * 24 * 60 * 60 * 1000));

  for (let t = earliest.getTime(); t <= latest.getTime(); t += PARTITION_PERIOD_MS) {
    await ensurePartitionForPeriod(pool, new Date(t));
  }
}

export interface PartitionInfo {
  name: string;
  upperBound: Date;
}

const PARTITION_NAME_RE = /^logs_w(\d{4})(\d{2})(\d{2})$/;

/**
 * Lists the weekly `logs_wYYYYMMDD` partitions and their upper time
 * bound. The bound is derived from the name itself (which we control)
 * rather than parsed out of the partition's catalog expression, since
 * every partition this service creates is named after its own period
 * start.
 */
export async function listPartitions(pool: Pool): Promise<PartitionInfo[]> {
  const { rows } = await pool.query<{ name: string }>(
    `SELECT child.relname AS name
     FROM pg_inherits
     JOIN pg_class parent ON pg_inherits.inhparent = parent.oid
     JOIN pg_class child ON pg_inherits.inhrelid = child.oid
     WHERE parent.relname = 'logs' AND child.relname LIKE 'logs\\_w%'`,
  );

  const partitions: PartitionInfo[] = [];
  for (const row of rows) {
    const match = PARTITION_NAME_RE.exec(row.name);
    if (!match) continue;
    const [, y, m, d] = match as unknown as [string, string, string, string];
    const start = new Date(Date.UTC(Number(y), Number(m) - 1, Number(d)));
    const upperBound = new Date(start.getTime() + PARTITION_PERIOD_MS);
    partitions.push({ name: row.name, upperBound });
  }
  return partitions;
}

/**
 * Drops a partition outright. This is a metadata-only operation (no row
 * scan, no per-row WAL) so it neither holds a long lock nor bloats the
 * heap the way `DELETE FROM logs WHERE ...` would.
 */
export async function dropPartition(pool: Pool, name: string): Promise<void> {
  await pool.query(`DROP TABLE IF EXISTS ${quoteIdentifier(name)}`);
}

export function startPartitionMaintenanceLoop(
  pool: Pool,
  behindDays: number,
  aheadDays: number,
  intervalMs: number,
): () => void {
  const tick = async (): Promise<void> => {
    try {
      await ensureRecentPartitions(pool, behindDays, aheadDays);
    } catch (err) {
      console.error("Partition maintenance failed", err);
    }
  };

  const handle = setInterval(tick, intervalMs);
  return () => clearInterval(handle);
}
